create table if not exists members (
    member_id bigint generated by default as identity primary key,
    name text not null,
    need_to_eye_on text not null default '',
    created_at text not null
);

create table if not exists member_tracking (
    tracking_id bigint generated by default as identity primary key,
    member_id bigint not null references members(member_id) on delete cascade,
    week_name text not null,
    week_range text not null,
    task_name text not null,
    value_status text not null default '',
    conducted_by text not null default '',
    note_to_eye_on text not null default '',
    michael_mark text not null default '',
    shift_runner_mark text not null default '',
    weekly_progress text not null default '',
    overall_score text not null default '',
    updated_at text not null,
    unique (member_id, week_name, task_name)
);

create table if not exists access_users (
    user_id bigint generated by default as identity primary key,
    name text not null,
    access_code text not null unique,
    role text not null default 'write',
    created_at text not null
);

alter table members add column if not exists member_id bigint generated by default as identity;
alter table members add column if not exists name text not null default '';
alter table members add column if not exists need_to_eye_on text not null default '';
alter table members add column if not exists created_at text not null default '';

alter table member_tracking add column if not exists tracking_id bigint generated by default as identity;
alter table member_tracking add column if not exists member_id bigint;
alter table member_tracking add column if not exists week_name text not null default '';
alter table member_tracking add column if not exists week_range text not null default '';
alter table member_tracking add column if not exists task_name text not null default '';
alter table member_tracking add column if not exists value_status text not null default '';
alter table member_tracking add column if not exists conducted_by text not null default '';
alter table member_tracking add column if not exists note_to_eye_on text not null default '';
alter table member_tracking add column if not exists michael_mark text not null default '';
alter table member_tracking add column if not exists shift_runner_mark text not null default '';
alter table member_tracking add column if not exists weekly_progress text not null default '';
alter table member_tracking add column if not exists overall_score text not null default '';
alter table member_tracking add column if not exists updated_at text not null default '';

alter table access_users add column if not exists user_id bigint generated by default as identity;
alter table access_users add column if not exists name text not null default '';
alter table access_users add column if not exists access_code text not null default '';
alter table access_users add column if not exists role text not null default 'write';
alter table access_users add column if not exists created_at text not null default '';

create unique index if not exists member_tracking_member_week_task_idx
on member_tracking (member_id, week_name, task_name);

create unique index if not exists access_users_access_code_idx
on access_users (access_code);
